In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#資料為xor真值表
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
X_label = np.array([[0], [1], [1], [0]])
Y = np.array([[0.3], [0.7], [0.7], [0.3]])

In [3]:
t_ = 15 #訓練回數
d_ = 4 #樣本數
n = 2 #神經元數量
m = 2 #輸入的資料維度  
p = 1 #輸出值維度

In [4]:
#定義參數
weight_v = [[1.0, -1.0], [-1.0, 1.0]]
weight_w = [[1.0], [1.0]]

theta_hj = np.ones((n, 1))
net_hj = np.zeros_like(theta_hj)
Hj = np.zeros_like(theta_hj) 
theta_k = np.ones((p, 1))
net_k =  np.zeros((p, 1))
Yk = np.array([0, 0, 0, 0], dtype = 'float64')
delta_k = np.zeros_like(net_k)
delta_hj = np.zeros_like(Hj)
eta = 10

In [5]:
for t in range(t_): #T iterations
    for d in range(d_): #D input samples
        xi = X[d]
        Tk = Y[d]
        #forward
        #compute hidden layer
        for j in range(n):
            #net_hj <- -theta_hj
            net_hj[j] = net_hj[j] - theta_hj[j]
            for i in range(m):
                #net_hj = net_hj + vij * xi
                net_hj[j] += weight_v[i][j] * xi[i]
            #Hj = 1/(1 + exp^-net_hj)
            Hj[j] = 1.0 / (1.0 + np.exp(-net_hj[j]))
            
        #compute output layer
        for k in range(p):
            #neth_k <- -theta_hk
            net_k[k] = net_k[k] - theta_k[k]
            for j in range(n):
                #neth_k = neth_k + wjk * Hj
                net_k[k] += weight_w[j][k] * Hj[j]
            #Yk = 1/(1 + exp^-net_k)
            Yk[d] = 1.0 / (1.0 + np.exp(-net_k[k]))
            
        #backward
        #compute delta for outputlayer
        for k in range(p):
            #delta_k = Yk * (1 - Yk) * (Tk - Yk)
            delta_k[k] = Yk[d] * (1.0 - Yk[d]) * (Tk - Yk[d]) 
        #compute delta for hidden layer
        for j in range(n):
            #delta_hj = 0
            delta_hj[j] = 0
            for k in range(p):
                #delta_hj = delta_hj + wjk * delta_k
                delta_hj[j] += (weight_w[j][k] * delta_k[k]) - (eta * delta_k[k])
            #delta_hj = Hj * (1 - Hj) * delta_hj
            delta_hj[j] = Hj[j] * (1.0 - Hj[j]) * delta_hj[j]
            
        #adjust parameters
        for k in range(p):
            #theta_k = theta_k - eta * delta_k
            theta_k[k] = theta_k[k] - (eta * delta_k[k])
            for j in range(n):
                #wjk = wjk + eta * delta_k * Hj
                weight_w[j][k] = weight_w[j][k] + (eta * delta_k[k] * Hj[j])
            for j in range(n):
                #theta_hj = theta_hj - eta * delta_hj
                theta_hj[j] = theta_hj[j] - (eta * delta_hj[j])
                for i in range(m):
                    #vij = vij + eta * delta_hj * xi
                    weight_v[i][j] = weight_v[i][j] + (eta * delta_hj[j] * xi[i])

    print('Yk =')
    print(Yk)
    print('epoch: %d'%(t))

Yk =
[0.3864837  0.25242223 0.31683894 0.43099858]
epoch: 0
Yk =
[0.46894648 0.40204313 0.51162616 0.72320697]
epoch: 1
Yk =
[0.73636323 0.5613746  0.45206649 0.49568625]
epoch: 2
Yk =
[0.41790844 0.2824582  0.33470508 0.59188642]
epoch: 3
Yk =
[0.67380544 0.56402959 0.53095257 0.60142455]
epoch: 4
Yk =
[0.49407171 0.28010438 0.26552029 0.43937987]
epoch: 5
Yk =
[0.54656095 0.501548   0.57974442 0.71712566]
epoch: 6
Yk =
[0.66654639 0.41102474 0.32904526 0.43873229]
epoch: 7
Yk =
[0.46960405 0.39661191 0.50214249 0.71735457]
epoch: 8
Yk =
[0.73262239 0.55900126 0.45359379 0.50031954]
epoch: 9
Yk =
[0.42260669 0.28401858 0.33375713 0.58819846]
epoch: 10
Yk =
[0.66956299 0.5592807  0.52924921 0.60382634]
epoch: 11
Yk =
[0.49973094 0.28436458 0.26915237 0.44338796]
epoch: 12
Yk =
[0.54740871 0.49871869 0.57511299 0.71418212]
epoch: 13
Yk =
[0.66449035 0.41056037 0.330434   0.44197728]
epoch: 14


In [6]:
#recall
for d in range(d_): #D input samples
        xi = X[d]
        Tk = Y[d]
        #forward
        #compute hidden layer
        for j in range(n):
            #net_hj <- -theta_hj
            net_hj[j] = net_hj[j] - theta_hj[j]
            weight_v_j = 0
            for i in range(m):
                #net_hj = net_hj + vij * xi
                weight_v_j += weight_v[i][j] * xi[i]
            net_hj[j] = net_hj[j] + weight_v_j
            #Hj = 1/(1 + exp^-net_hj)
            Hj[j] = 1/(1 + np.exp(-net_hj[j]))
            
        #compute output layer
        for k in range(p):
            #neth_k <- -theta_hk
            net_k[k] = net_k[k] - theta_k[k]
            for j in range(n):
                #neth_k = neth_k + wjk * Hj
                net_k[k] += weight_w[j][k] * Hj[j]
            #Yk = 1/(1 + exp^-net_k)
            Yk[d] = 1/(1.0 + np.exp(-net_k[k]))
            """
            if Yk[d] >= 0.5:
                Yk[d] = 1
            else:
                Yk[d] = 0
            """
print(Yk)

[0.47247212 0.50317378 0.53385152 0.56427534]
